# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    # point dependabot to our develop branch. TODO add a wildcard to the end so it screens for each of our develop branchs from sprints
    target-branch: "develop"
    # Labels on pull requests for version updates only
    labels:
      - "dependencies"
