name: "Perform static analysis"
description: "Perform static analysis"
inputs:
  sonar_token:
    description: "Sonar token API key"
    required: false
  sonar_project_key:
    description: "Sonar Project key"
    required: true
  sonar_organisation_key:
    description: "Sonar Org key"
    required: true
runs:
  using: "composite"
  steps:
    - name: install node 20 to test if that fixes sonar scanner issue
      shell: bash
      run: |
        export NVM_DIR="/home/runner/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        nvm install 18 --lts
        node -v
        echo "Setting PATH..."
        echo "PATH=$NVM_DIR/versions/node/$(node -v)/bin:$PATH" >> $GITHUB_ENV
        which node
    - name: "Check prerequisites for performing static analysis"
      shell: bash
      id: check
      run: echo "secret_exist=${{ inputs.sonar_token != '' }}" >> $GITHUB_OUTPUT
    - name: "Perform static analysis"
      shell: bash
      if: steps.check.outputs.secret_exist == 'true'
      run: |
        echo "using node version:"
        node -v
        export BRANCH_NAME=${GITHUB_HEAD_REF:-$(echo $GITHUB_REF | sed 's#refs/heads/##')}
        export SONAR_TOKEN=${{ inputs.sonar_token }}
        export SONAR_ORGANISATION_KEY=${{ inputs.sonar_organisation_key }}
        export SONAR_PROJECT_KEY=${{ inputs.sonar_project_key }}
        ./scripts/reports/perform-static-analysis.sh
