# See:
# - https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository
# - https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms
# - https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/common-validation-errors-when-creating-issue-forms

name: 🐞 Bug Report
description: File a bug report
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to file a bug report. Please fill out this form as completely as possible.
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please, search the Issues to see if an issue already exists for the bug you have encountered.
      options:
      - label: I have searched the existing Issues
        required: true
  - type: textarea
    attributes:
      label: Current Behavior
      description: A concise description of what you are experiencing.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expect to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run `...`
    validations:
      required: false
  - type: textarea
    attributes:
      label: Output
      description: Please copy and paste any relevant output. This will be automatically formatted into codeblock.
      render: Shell
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Code of Conduct
      description: By submitting this issue you agree to follow our [Code of Conduct](../../docs/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
  - type: checkboxes
    attributes:
      label: Sensitive Information Declaration
      description: To ensure the utmost confidentiality and protect your privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this form. We appreciate your cooperation in maintaining the security of your information.
      options:
        - label: I confirm that neither PII/PID nor sensitive data are included in this form
          required: true
