name: "Versioning"
description: "Tags repository with the next version"

runs:
  using: "composite"
  steps:
    - name: "Checkout code"
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: "Tag with next release version"
      shell: bash
      run: |
        ./scripts/pipeline/version.sh ${{ env.version_bump }}
