name: Check Test Coverage

on:
  workflow_call:

jobs:
  check-file-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          npm i
          npm run coverage
          pwd
          ls -l
