name: Scan Secrets

on:
  workflow_call:

jobs:
  scan-secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          export ALL_FILES=true
          ./scripts/githooks/secret-scan-pre-commit.sh
