name: "Perform static analysis"
description: "Perform static analysis"
runs:
  using: "composite"
  steps:
    - name: "Check prerequisites for performing static analysis"
      shell: bash
      id: check
      run: npm i
    - name: "Perform static analysis"
      shell: bash
      if: steps.check.outputs.secret_exist == 'true'
      run: npm run coverage
