name: "Perform static analysis"
description: "Perform static analysis"
runs:
  using: "composite"
  steps:
    - name: "Check prerequisites for performing static analysis"
      shell: bash
      run: npm i
    - name: "Perform static analysis"
      shell: bash
      run: npm run coverage
